### ISSUE TITLE
Add a variable docker_apt_filename to control apt repository filename

### ISSUE THREAD

**Issue by julien-lecomte** [geerlingguy/ansible-role-docker#101]
Feature Request:

Add a variable docker_apt_filename to control apt repository filename. Default to ansible apt_repository default's (https://docs.ansible.com/ansible/2.6/modules/apt_repository_module.html)

**Comment by geerlingguy** [comment]
Can you give a little more detail as to why you would like more control over the filename? I haven't had to do this before, but if it's a common need I would be okay supporting it.

**Comment by julien-lecomte** [comment]
Is OCD a valid reason? ;-)

My reason is that I have legacy scripts that use the file names to activate / deactive sources and packages and other actions based on filename. ie: On the buster system I have under my hand right now I have debian-buster.list, debian-buster-updates.list, debian-buster-security.list, and docker-ce.list; each with only one line.

I don't know how common this is, but at worst it adds an optional functionality without breaking existing behavior.
I'd reason that if it was added to ansible in 2.1, there must have been a need.

**Comment by julien-lecomte** [comment]
Hi
May I ask for an update on this? Most notably, will you accept to merge the associated MR?
Thanks,
Julien
