### ISSUE TITLE
Feature request: allow Docker downgrade

### ISSUE THREAD

**Issue by donhector** [geerlingguy/ansible-role-docker#121]
### Use case
You deploy Docker to your fleet using this role and its defaults. This will deploy the latest version of Docker available in the platform repos (in my case, I'm running Ubuntu 16.04 and I'm getting 18.09.1 at the time of writing). Then you find a bug in 18.09.1 and want to downgrade to an earlier version, also available in the platform repo, for example: 18.06.1

So I re-ran the role but this time overriding the `docker_package` variable pinning it to an earlier package version like this: `docker_package: docker-ce=18.06.1~ce~3-0~ubuntu`

This is the error I got:

```
TASK [geerlingguy.docker : include_tasks] **********************************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.docker : include_tasks] **********************************************************************************************************************************************************************************************************************************
included: /exports/nfs/workdir/business-events/.bootstrap/ansible/roles/galaxy/geerlingguy.docker/tasks/setup-Debian.yml for 127.0.0.1

TASK [geerlingguy.docker : Ensure old versions of Docker are not installed.] ***********************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.docker : Ensure dependencies are installed.] *************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.docker : Add Docker apt key.] ****************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.docker : Ensure curl is present (on older systems without SNI).] *****************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.docker : Add Docker apt key (alternative for older systems without SNI).] ********************************************************************************************************************************************************************************
skipping: [127.0.0.1]

TASK [geerlingguy.docker : Add Docker repository.] *************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [geerlingguy.docker : Install Docker.] ********************************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"cache_update_time": 1549518332, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'docker-ce=18.06.1~ce~3-0~ubuntu'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.\n", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  containerd.io linux-gcp-tools-4.15.0-1025 linux-gcp-tools-4.15.0-1026\nUse 'sudo apt autoremove' to remove them.\nThe following packages will be REMOVED:\n  docker-ce-cli\nThe following packages will be DOWNGRADED:\n  docker-ce\n0 upgraded, 0 newly installed, 1 downgraded, 1 to remove and 0 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  containerd.io linux-gcp-tools-4.15.0-1025 linux-gcp-tools-4.15.0-1026", "Use 'sudo apt autoremove' to remove them.", "The following packages will be REMOVED:", "  docker-ce-cli", "The following packages will be DOWNGRADED:", "  docker-ce", "0 upgraded, 0 newly installed, 1 downgraded, 1 to remove and 0 not upgraded."]}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=18   changed=3    unreachable=0    failed=1   
```

After that, `docker version` still shows I'm on 18.09.1

Have you ever considered this use case? 

Thank you!

**Comment by rokcarl** [comment]
I have a slightly different problem. I'm on `docker-ce=5:19.03.8~3-0~debian-stretch`, but now after upgrading the system to Debian 10 from Debian 9, this role wants to install `docker-ce=5:19.03.8~3-0~debian-buster` (same version as before, only the distribution release is different). When running, I get the error `E: Packages were downgraded and -y was used without --allow-downgrades.`. Here's the full error:

    TASK [geerlingguy.docker : Install Docker.] ******************************************************************************************************************************************
    fatal: [test-routing-1]: FAILED! => {"cache_update_time": 1587965107, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'docker-ce=5:19.03.8~3-0~debian-buster'' failed: E: Packages were downgraded and -y was used without --allow-downgrades.\n", "rc": 100, "stderr": "E: Packages were downgraded and -y was used without --allow-downgrades.\n", "stderr_lines": ["E: Packages were downgraded and -y was used without --allow-downgrades."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nRecommended packages:\n  aufs-tools cgroupfs-mount | cgroup-lite pigz\nThe following packages will be DOWNGRADED:\n  docker-ce\n0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Recommended packages:", "  aufs-tools cgroupfs-mount | cgroup-lite pigz", "The following packages will be DOWNGRADED:", "  docker-ce", "0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded."]}

I get the same error if I run `apt-get install -y docker-ce=5:19.03.8~3-0~debian-buster` manually on the server. If I simply add the `--allow-downgrades`, it goes through.

**Comment by rokcarl** [comment]
I found out that there's a pull request in Ansible that would allow this to be added to this role:
https://github.com/ansible/ansible/pull/33677

**Comment by amotl** [comment]
Dear @donhector and @rokcarl,

we just submitted #317, which might resolve this issue. Based on this, we have been able to accomplish to install a specific version (`docker_edition: "ce=5:20.10.10*"`), even if 20.10.11 has been installed before, see also https://github.com/geerlingguy/ansible-role-docker/issues/307#issuecomment-978086817.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Because the original PR #317 got stale, I've just submitted it again at #336.
