### ISSUE TITLE
Provide a way to upgrade Docker package

### ISSUE THREAD

**Issue by kakawait** [geerlingguy/ansible-role-docker#14]
What do you think about offering the possibility to upgrade Docker version by simply not hard-code `state=present` 

Example from other role (random pick) https://github.com/angstwad/docker.ubuntu/blob/master/tasks/main.yml#L97

**Comment by geerlingguy** [comment]
Definitely! I would probably implement it by adding a variable `docker_package_state` or something like that. Default it to `present`, but if you change it to `latest`, it would always ensure the latest version is installed.

**Comment by kakawait** [comment]
Nice I may post a PR. Is not a big deal to implement

_Sent from my Oneplus A0001 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
