### ISSUE TITLE
Add support to Amazon Linux

### ISSUE THREAD

**Issue by bkmeneguello** [geerlingguy/ansible-role-docker#141]
As per [documentation](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html#install_docker) it "only" requires executing
```bash
sudo amazon-linux-extras install docker
```

**Comment by ElijahLynn** [comment]
Thanks for opening this. 

I am coming across this in some other roles too, and here is where Amazon Linux is definitely not CentOS. So, is the right step here to just override the `ansible_distribution_major_version` var or rewrite things to accommodate?

`cat /etc/system-release`
> Amazon Linux AMI release 2018.03

`ansible --inventory inventory --user ec2-user all --module setup`
> "ansible_distribution": "Amazon",
> "ansible_distribution_file_parsed": true,
> "ansible_distribution_file_path": "/etc/system-release",
> "ansible_distribution_file_variety": "Amazon",
> "ansible_distribution_major_version": "2018",
> "ansible_distribution_release": "NA",
> "ansible_distribution_version": "NA",

**Comment by bkmeneguello** [comment]
Hi, I really don't know. I usually install docker through  `amazon-linux-extras install docker`
Whenever I try to install it like I do with CentOS It fails with some dependencies missing.
