### ISSUE TITLE
Docker CE can't be installed on Ubuntu 19.04

### ISSUE THREAD

**Issue by declension** [geerlingguy/ansible-role-docker#144]
### Steps
Run the playbook on a fresh Ubuntu 19.04 machine. 

e.g. using this `Dockerfile` (note it's working around #124 for now):

```Dockerfile
FROM ubuntu:19.04

RUN apt-get -qq update && apt-get install -qq ansible gnupg
RUN ansible-galaxy install geerlingguy.docker

RUN echo "- hosts: localhost\n  roles:\n  - geerlingguy.docker" > playbook.yml
RUN ansible-playbook playbook.yml
```

### Expected
Successful installation of Docker etc.

### Actual
Fails with message `No package matching 'docker-ce' is available`
```
TASK [geerlingguy.docker : Install Docker.] **************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}
        to retry, use: --limit @/playbook.retry
```

**Comment by MarcDiethelm** [comment]
I'm also seeing this with Armbian Bionic (18.04)

**Comment by bjonnh** [comment]
I don't know for bionic, but for disco on amd64 you have to use the test level:
by setting the variable:
docker_apt_release_channel: "test"

then it installs properly. It is due to the fact that docker doesn't have a stable release yet in their repo.

**Comment by declension** [comment]
Thanks @bjonnh, I can confirm that fix / workaround is successful!

**Comment by geerlingguy** [comment]
Thanks @bjonnh for the workaround! Note that I do not officially support non-LTS releases in any of my roles because it is usually too much of a moving target (and things like this crop up all the time). So I'm closing this issue but hopefully the information inside will help others searching the same problem!

**Comment by MarcDiethelm** [comment]
In my case (Armbian Bionic 18.04 LTS, Ansible v2.8.1) the workaround is not successful also it should not be needed as just using apt manually Docker installs fine. I'm stumped (and blocked). Should I create a new issue? I'd really appreciate some help in debugging/solving this.

**Comment by pdamoune** [comment]
Just had the same issue trying to install docker on a french 'Freebox' VM that seems to be a Rasberry Pi with Ubuntu 20.04

I found out by reading the docker doc:
`deb [arch=$(dpkg --print-architecture) signed-by=(...)`
and my arch was `arm64`

In the geerlingguy.docker role, this variable `docker_apt_arch` is set by default to `amd64` when i needed to set it to `arm64` 
(dpkg --print-architecture)

unfortunately it can't be set with the `ansible_architecture` variable:
    `"aarch64": "VARIABLE IS NOT DEFINED!"`

Solution:
    docker_apt_arch: arm64
