### ISSUE TITLE
Installation fails on debian 10

### ISSUE THREAD

**Issue by FabienPapet** [geerlingguy/ansible-role-docker#150]
Seems like installation is broken on debian 10. The playbook still runs well.

Using default role without any configuration (2.5.2)

Installed version : Docker version 19.03.1, build 74b1e89

```sh
# with root user 
docker run --rm hello-world
docker: Error response from daemon: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default109897368` failed with output: AppArmor parser error for /var/lib/docker/tmp/docker-default109897368 in /etc/apparmor.d/tunables/global at line 17: Could not open 'tunables/proc'

error: exit status 1.
```

**Comment by lhilton** [comment]
Any solution to this yet?

**Comment by FabienPapet** [comment]
Resetting and reinstalling the server worked for me.

**Comment by alqu** [comment]
I installed `Debian v10.1` and applied this role on it:
It worked flawlessly.
Afterwards, `Docker version 19.03.5, build 633a0ea838` has been installed.

So I think this ticket is obsolete.

**Comment by geerlingguy** [comment]
Could be, but I'll add a debian10 test to the CI test suite and see if it works.

**Comment by geerlingguy** [comment]
It seems to work well in CI now, so I'm guessing it should be working in other environments with Debian 10 :)
