### ISSUE TITLE
Force docker-ce and docker-ce-cli to same version

### ISSUE THREAD

**Issue by andrey-ciandt** [geerlingguy/ansible-role-docker#152]
Hey need some help with forcing the docker-ce version to a specific one.

I am using the line below to specify it, and it works for docker-ce package 
`docker_package: 'docker-{{ docker_edition }}=5:18.09.7~3-0~ubuntu-xenial'`
But apt automatcally downloads a dependency named docker-ce-cli, which is using the latest version.

There is a way to force both?

**Comment by pandvan** [comment]
I'm running into the same problem and looking for an elegant solution.
