### ISSUE TITLE
Feature Request - Install a specific version of docker

### ISSUE THREAD

**Issue by ernestomedina17** [geerlingguy/ansible-role-docker#156]
I want this because Kubernetes does not uses the latest Docker release, so I want to specify the version. E.g.:
WARNING SystemVerification: this Docker version is not on the list of validated versions: 19.03.2. Latest validated version: 18.09

**Comment by Zigzauer** [comment]
Hello. It does support version specification , it's just weird package naming for 19+ docker versions . Try using it like 
`vars:
     docker_package:` "docker-ce=5:19.03.2~3-0~ubuntu-bionic"

**Comment by ernestomedina17** [comment]
I tried with the "=" but din't worked in CentOS 7, however it worked with this string:
```
vars:
  docker_package: "3:docker-ce-18.09.9-3.el7.x86_64"
```

Which I got from this command: 
   `yum search docker-ce --show-duplicates | grep 18.09 `

So I'm closing this one, thank you very much.

**Comment by Sn0rt** [comment]
how to do this for ubuntu ?
