### ISSUE TITLE
Possibility to skip handler

### ISSUE THREAD

**Issue by hypery2k** [geerlingguy/ansible-role-docker#169]
Would be great to have the option to skip the handler.

I'm using the role in a packer setup for building docker images and the restart wouldn't work there ...

**Comment by geerlingguy** [comment]
One way to effectively do this (I have the same issue, as I use this in docker images quite frequently) is to set:

```
docker_restart_handler_state: stopped
```

(Or `started` if it should be started but not restarted.)
