### ISSUE TITLE
add possibility to define a custom /var/lib/docker path 

### ISSUE THREAD

**Issue by BlowaXD** [geerlingguy/ansible-role-docker#176]
Hi,

I have some bare metal servers that are running docker for my project.
My issue is that I'm having issues on disk limitations on / and I have a lot of space on /mnt/XXXXX mounted partitions

https://forums.docker.com/t/how-do-i-change-the-docker-image-installation-directory/1169/6 this seems to make me able to fix my disk space issue, but I don't want to configure it by hand since all my servers are getting provisioned by Ansible.

It looks like adding the following line :
`DOCKER_OPTS="-g /path/to/my/expected/docker/saving/directory"`
to the file : `/etc/default/docker` works.

Do you think we could add that possibility to this role ? 
I can't install every platforms to test it, I'm personally using Ubuntu so it should work for most Debian based solutions ? I'm still a beginner on Ansible, I don't know a good way to handle that on every platforms.

Any tips ?

Thanks by advance

**Comment by acurvers** [comment]
i like to be able to add this DOCKER_OPTS="--iptables=false"
