### ISSUE TITLE
usage within corporate proxy fails

### ISSUE THREAD

**Issue by gthieleb** [geerlingguy/ansible-role-docker#187]
Usage of the docker role on Centos/RHEL and behind corporate proxy currently fails on task `rpm_key`.
Reason and error log is described here: ansible/ansible#38050

**Comment by gthieleb** [comment]
nevermind, it was a local problem. 
`rpm_key` seems to work with remote file and usign a proxy.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-role-docker/pull/174
