### ISSUE TITLE
Debian system and pipefail

### ISSUE THREAD

**Issue by zoredache** [geerlingguy/ansible-role-docker#188]
I know you are [aware of this](https://github.com/ansible/ansible-lint/issues/497) but this seems to be a pipefail option, on a Debian buster system.  Debian defaults to dash, which is not bash.  It does not have `-o pipefail`.

https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-Debian.yml#L29

> TASK [geerlingguy.docker : Add Docker apt key (alternative for older systems without SNI).] ***************************
> fatal: [web-01.remote]: FAILED! => {"changed": true, "cmd": "set -o pipefail\ncurl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -\n", "delta": "0:00:00.002110", "end": "2020-02-27 10:50:52.777772", "msg": "non-zero return code", "rc": 2, "start": "2020-02-27 10:50:52.775662", "stderr": "/bin/sh: 1: set: Illegal option -o pipefail", "stderr_lines": ["/bin/sh: 1: set: Illegal option -o pipefail"], "stdout": "", "stdout_lines": []}

Oh, and yes, I know there are workarounds, just thought I would add the issue here.  My temporary workaround was to set a executable for shell in the module_defaults of my play.

    - hosts: web-01.remote
      module_defaults:
        shell:
          executable: /bin/bash
      tasks:
      - include_role:
          name: geerlingguy.docker
      ...

**Comment by geerlingguy** [comment]
You're correct—that should be removed... that was added when `ansible-lint` started forcing the use of `pipefail` on shell tasks, even though pipefail isn't present on a _number_ of different systems. D'oh!
