### ISSUE TITLE
Docker has issues with Debain 10 Buster nftables - needs revert to iptables-legacy

### ISSUE THREAD

**Issue by misi** [geerlingguy/ansible-role-docker#189]
Hi,

I think this role should revert iptables alternatives to legacy. Without it it fails docker-compose up

e.g. 
```
Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (iptables failed: iptables --wait -t nat -I DOCKER -i br-e9d090e21636 -j RETURN: iptables v1.8.2 (nf_tables): Chain 'DOCKER' does not exist\n (exit stat
us 1)) 
```

**Comment by geerlingguy** [comment]
Note that the _installation_ at least works fine on Debian 10—see https://github.com/geerlingguy/ansible-role-docker/blob/master/.travis.yml#L13

I do have a task like this in my pi dramble project (which runs on Raspbian 10): https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/tasks/iptables-legacy.yml

**Comment by misi** [comment]
@geerlingguy 
You are right that this role runs without error, but without reverting back iptables to legacy, it will not work properly AFAIU. So if I want to run docker-compose I get this error. 
I created a similar task as you mentioned.. 
If you don't want to add this revert task, then I still think to avoid  any confusion, it still worth to add a warning about it on Debian 10. 

Thanks for your fast reply!

**Comment by geerlingguy** [comment]
Linking to the upstream issue: https://github.com/moby/moby/issues/26824

**Comment by geerlingguy** [comment]
And related issue in kubernetes project: https://github.com/kubernetes/kubernetes/issues/71305

**Comment by waynr** [comment]
Since I disable docker's iptables via daemon.json to accommodate my nft rulesets (which include a modified version of what docker sets up anyway), I would be surprised and annoyed if an ansible role made a system-wide alternatives change to work around docker's bad behavior with regard to nf_tables.
