### ISSUE TITLE
gnupg2 install breaks Ubuntu 18.04

### ISSUE THREAD

**Issue by lod** [geerlingguy/ansible-role-docker#195]
The install of gnupg2 added in commit a19ed5612847c94c3fe70905b379bbf970f3d6e4 breaks Ubuntu 18.04, the current Ubuntu LTS

The same flaw also impacts your gitlab role https://github.com/geerlingguy/ansible-role-gitlab/issues/149

**Comment by PavelSheremetev** [comment]
fix if manually run `apt update --fix-missing` on Ubuntu 18.04 and rerun tasks

**Comment by geerlingguy** [comment]
@lod - I added it to fix some issues with Debian 10, and in my own local tests in both a Docker container with a minimal install as well as in a VirtualBox VM with the Ubuntu server install, I haven't had any issues. Can you provide more information about what task, in particular, is failing, along with any associated error messages?

**Comment by geerlingguy** [comment]
Could it be a possibility that the apt caches were out of date, and just running `apt-get update` prior to this (or having your Ansible playbook add an `update_cache` task) would fix it?

https://github.com/geerlingguy/ansible-role-docker/blob/master/molecule/default/converge.yml#L6-L9

**Comment by nlsdfnbch** [comment]
Running `- apt: {update_cache: yes}` in my playbook's `pre_tasks` fixed the issue for me. Thanks for the pointer!

**Comment by dyasny** [comment]
I added `apt: {update_cache: yes}` as a pre_task, and it allowed the role to go further, but it failed nonetheless:

```
TASK [geerlingguy.docker : Ensure dependencies are installed.] ***********************************************************************************************
task path: /home/dyasny/.ansible/roles/geerlingguy.docker/tasks/setup-Debian.yml:9
fatal: [1.2.3.4]: FAILED! => {"changed": false, "msg": "'/usr/bin/apt-mark manual apt-transport-https ca-certificates gnupg2' failed: E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "rc": 100, "stderr": "E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE: Failed to write temporary StateFile /var/lib/apt/extended_states\n", "stderr_lines": ["E: Could not create temporary file for /var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E: Failed to write temporary StateFile /var/lib/apt/extended_states"], "stdout": "apt-transport-https can not be marked as it is not installed.\nca-certificates set to manually installed.\ngnupg2 can not be marked as it is not installed.\n", "stdout_lines": ["apt-transport-https can not be marked as it is not installed.", "ca-certificates set to manually installed.", "gnupg2 can not be marked as it is not installed."]}
META: noop
META: noop
META: noop
META: noop

```

**Comment by deepbrook** [comment]
Run `- {apt: {update_cache: yes}} ` in pre_tasks, that  should take care of that.

On 22 July 2020 19:31:24 CEST, Dan Yasny <notifications@github.com> wrote:
>I added `apt: {update_cache: yes}` as a pre_task, and it allowed the
>role to go further, but it failed nonetheless:
>
>```
>TASK [geerlingguy.docker : Ensure dependencies are installed.]
>***********************************************************************************************
>task path:
>/home/dyasny/.ansible/roles/geerlingguy.docker/tasks/setup-Debian.yml:9
>fatal: [1.2.3.4]: FAILED! => {"changed": false, "msg":
>"'/usr/bin/apt-mark manual apt-transport-https ca-certificates gnupg2'
>failed: E: Could not create temporary file for
>/var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE:
>Failed to write temporary StateFile /var/lib/apt/extended_states\n",
>"rc": 100, "stderr": "E: Could not create temporary file for
>/var/lib/apt/extended_states - mkstemp (13: Permission denied)\nE:
>Failed to write temporary StateFile /var/lib/apt/extended_states\n",
>"stderr_lines": ["E: Could not create temporary file for
>/var/lib/apt/extended_states - mkstemp (13: Permission denied)", "E:
>Failed to write temporary StateFile /var/lib/apt/extended_states"],
>"stdout": "apt-transport-https can not be marked as it is not
>installed.\nca-certificates set to manually installed.\ngnupg2 can not
>be marked as it is not installed.\n", "stdout_lines":
>["apt-transport-https can not be marked as it is not installed.",
>"ca-certificates set to manually installed.", "gnupg2 can not be marked
>as it is not installed."]}
>META: noop
>META: noop
>META: noop
>META: noop
>
>```
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/geerlingguy/ansible-role-docker/issues/195#issuecomment-662585921

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deepbrook** [comment]
It clearly states you are missing permissions. Set `become: yes`.

**Comment by dyasny** [comment]
That is a given, the role runs with become: true

**Comment by dyasny** [comment]
This is the playbook snipped a bit:

```
  vars:
    docker_users:
      - "{{ ansible_user }}"
  pre_tasks:
    - apt:
        update_cache: yes
      become: true
      when: ansible_os_family == "Debian"
  roles:
    - role: geerlingguy.docker
      when: install_type == "docker"
      become: true
```
