### ISSUE TITLE
Fedora 32 not supported

### ISSUE THREAD

**Issue by saibotk** [geerlingguy/ansible-role-docker#206]
The ansible galaxy metadata declares, that this role would be compatible with all Fedora versions, but version 32 won't work with this role, as there is no docker repository or official package available.

Maybe adjust https://github.com/geerlingguy/ansible-role-docker/blob/26297760a3a744acbf064e4659c3afe61849c872/meta/main.yml#L18 
to only match those versions, that are actually supported, so other users are not confused.

Thanks for your work and keep on going!
:+1:

**Comment by westurner** [comment]
See https://github.com/geerlingguy/ansible-role-docker/issues/105#issuecomment-638679438 regarding `dnf install -y moby-engine` and other requisite config steps for docker w/ fc32.

This also seems to work in the interim:
```bash
sed -i 's/\$releasever/31' /etc/yum/repos.d/[docker]
```

But that'll likely break in the future due to fc31/fc32 dependency mismatch?

**Comment by westurner** [comment]
Bump

**Comment by saibotk** [comment]
This is still incorrectly stated in the meta definition.

**Comment by fourstepper** [comment]
@saibotk just open a PR to remove the meta tag for now, idk if @geerlingguy is planning on supporting fedora 32 with a workaround such as installing Moby the official repos?

**Comment by saibotk** [comment]
> @saibotk just open a PR to remove the meta tag for now, idk if @geerlingguy is planning on supporting fedora 32 with a workaround such as installing Moby the official repos?

Honestly I'm actually unclear, if it is now supported, since docker has added repositories for F32/31 and lists them on their official site. I still want the meta.yml to actually reflect tested/verified systems instead.

**Comment by fourstepper** [comment]
I think the best thing to do would be to support the supported Fedora versions (32 & 33 now).

I have proposed a PR that adds Fedora 32 and Fedora 33 to CI. Based on that, other changes could be made.

**Comment by fourstepper** [comment]
This can be closed - implemented here: https://github.com/geerlingguy/ansible-role-docker/pull/250

**Comment by saibotk** [comment]
Thank you :rocket:
