### ISSUE TITLE
Recommended packages are not installed for Ubuntu 14.04 (Trusty)

### ISSUE THREAD

**Issue by it-praktyk** [geerlingguy/ansible-role-docker#22]
The quote from Docker documentation 

> Unless you have a strong reason not to, install the linux-image-extra-* packages, which allow Docker to use the aufs storage drivers.
> 
> ```
> $ sudo apt-get update
> 
> $ sudo apt-get install \
>    linux-image-extra-$(uname -r) \
>   linux-image-extra-virtual
> ```

Source: [Recommended extra packages for Trusty 14.04](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#recommended-extra-packages-for-trusty-1404)

Recommended packages are not installed by the current role. Should be?

**Comment by PhilThurston** [comment]
Good catch!

**Comment by geerlingguy** [comment]
I won't necessarily close this issue yet... but I haven't had any issues running Docker on Ubuntu 14.04 with this role, and it seems the daily cron build that runs on 14.04 hasn't had any installation failures either... https://travis-ci.org/geerlingguy/ansible-role-docker/builds/265841483
