### ISSUE TITLE
docker-compose.yml: Hardcoded x86_64 and no build for aarch64

### ISSUE THREAD

**Issue by nategadzhi** [geerlingguy/ansible-role-docker#220]
Hey @geerlingguy! Thanks for putting the role together! 

## Problem

Currently, the role installs `docker-compose` from github releases and has hardcoded amd64 arch. If I try running this on an aarch64 Ubuntu 20.04, I get, predictably, executable format error: 

```
rpi1:~/a/timemachine docker-compose status
Failed to execute process '/usr/local/bin/docker-compose'. Reason:
exec: Exec format error
The file '/usr/local/bin/docker-compose' is marked as an executable but could not be run by the operating system.
```

## Solution

There are three possible solutions for this: 
1. We could install docker-compose with pip (although that would bring managing all the virtualenv hell along with it, suboptimal). The same outcome could be reched with the following: 
   ```
      - role: geerlingguy.pip
        pip_install_packages:
          - name: docker-compose
   ```

2. Alternatively, we could optionally install docker-compose in the container (i.e. run.sh) only if `docker_apt_arch` is set to `aarch64` of 32 bit arm, for that matter. This is quite an esoteric way to install docker-compose though ;) 

3. And finally, we could _not_ install docker-compose in case `docker_apt_arch` is anything but amd64, since there are no readymade packages for these on github anyway. 

I'd be happy to implement any of those approaches, I personally think that approach 3 with a warning would be the cleanest. 

In my personal scenario, to be clear, just `pip install docker-compose` works fine in aarch64 systems. So if the user wants docker-compose executable, or if the user wants to use docker_compose Ansible module, they'll have to pip install it anyway. 

So maybe we should also change the documentation to reflect that ;) 

Happy to do a PR covering both.

**Comment by geerlingguy** [comment]
Please see: https://github.com/geerlingguy/ansible-role-docker_arm

**Comment by willianpaixao** [comment]
Hey @geerlingguy,
first of all, keep up the great work!

I believe that even tho you have an ARM specific role, the binary shouldn't be hardcoded to AMD64.
A condition like `when: ansible_architecture == "armv6l"` would fix that issue, maybe use the same variable you already implemented.

Let me know your thoughts and I can quickly send a PR.
