### ISSUE TITLE
failed to fetch key at https://download.docker.com/linux/centos/gpg , error was: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by anasri72** [geerlingguy/ansible-role-docker#227]
Hi Dear, 
I have an issue which is related to sanctions , mostly I have to use define proxy for yum to be able to download a package but how can I do the same for ansible? 
The following report is a vast problem here where I live. 

fatal: [teleport]: FAILED! => {"changed": false, "msg": "failed to fetch key at https://download.docker.com/linux/centos/gpg , error was: HTTP Error 403: Forbidden"}

**Comment by p3im4n** [comment]
hi
I have this is problem too
