### ISSUE TITLE
unable to install docker

### ISSUE THREAD

**Issue by anasri72** [geerlingguy/ansible-role-docker#228]
THello Dear, I have got a fresh server and decided to install docker via your ansbile role, but it failed and stuck in the following line. 

note that I could install docker via yum manually. 

TASK [geerlingguy.docker : Install Docker.] ************************************************************************************************
task path: /home/ansible/.ansible/roles/geerlingguy.docker/tasks/main.yml:8
fatal: [teleport]: FAILED! => {"changed": false, "changes": {"installed": ["docker-ce"]}, "msg": "http://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/checkpolicy-2.5-8.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/audit-libs-python-2.8.5-4.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/libcgroup-0.41-21.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/extras/x86_64/Packages/container-selinux-2.119.2-1.911c772.el7_8.noarch.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/libsemanage-python-2.5-14.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/policycoreutils-python-2.5-34.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/python-IPy-0.75-6.el7.noarch.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.fr.planethoster.net/7.8.2003/os/x86_64/Packages/setools-libs-3.3.8-4.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirror.ate.info/7.8.2003/os/x86_64/Packages/checkpolicy-2.5-8.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://mirrors.atosworldline.com/public/centos/7.8.2003/os/x86_64/Packages/audit-libs-python-2.8.5-4.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://centos.mirrors.proxad.net/7.8.2003/extras/x86_64/Packages/container-selinux-2.119.2-1.911c772.el7_8.noarch.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://ftp.pasteur.fr/mirrors/CentOS/7.8.2003/os/x86_64/Packages/libcgroup-0.41-21.el7.x86_64.rpm: [Errno 14] curl#56 - \"Recv failure: Connection reset by peer\"\nTrying other mirror.\nhttp://mirrors.standaloneinstaller.com/centos/7.8.2003/os/x86_64/Pack

**Comment by AnimeshMittal** [comment]
I am also facing the same issue...
'Install Docker' task keeps playing for hours without any output. It works fine manually through yum.

![DockerInstallation_Problem](https://user-images.githubusercontent.com/56085602/93510200-74bc2f80-f93e-11ea-82fe-95e9c00ab547.jpg)

**Comment by AnimeshMittal** [comment]
After around 4 hours in hung state, it errored out with similar error:

![image](https://user-images.githubusercontent.com/56085602/93579033-9f000280-f9bb-11ea-8e4e-b8172d8b4373.png)
