### ISSUE TITLE
Fails with Ubuntu 20.10 (Groovy Gorilla)

### ISSUE THREAD

**Issue by darkn3rd** [geerlingguy/ansible-role-docker#240]
This fails with Ubuntu 20.10 (Groovy Gorilla) as there's no repository area for this explicit name.  It should be flexible enough to install packages for 20.04 on 20.10.

**Comment by geerlingguy** [comment]
@darkn3rd - For my roles, I only support LTS releases of Ubuntu (.04 releases). Thanks for posting the issue, but I do not plan on supporting non-LTS for now.
