### ISSUE TITLE
Feature request - add a user to the docker group

### ISSUE THREAD

**Issue by jamesla** [geerlingguy/ansible-role-docker#25]
Hi thanks for making this role. I have some feedback. I think that this role should consider adding a user to the docker group to allow users to run docker

**Comment by jamesla** [comment]
https://github.com/geerlingguy/ansible-role-docker/pull/26/files

**Comment by jamesla** [comment]
bump

**Comment by loicortola** [comment]
@geerlingguy are you still alive? =)

**Comment by jamesla** [comment]
I’m fairly certain he died

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-docker/pull/26

Not dead, yet :D
