### ISSUE TITLE
Docker is not working on redhat 8 

### ISSUE THREAD

**Issue by hamdirhibi** [geerlingguy/ansible-role-docker#253]

**Comment by dszmaj** [comment]
agree, it should not be marked as rhel 8 compatible if the only thing it does is to install containerd.io

**Comment by geerlingguy** [comment]
But... it is? At least the automation works... honestly I'm disgusted by the CentOS 8 debacle, so I kinda halted working on any RHEL8/CentOS 8 testing and compatibility in my roles for now.

**Comment by dverbeek84** [comment]
Works fine, you just need to install iptables to be able to start docker.
Maybe it should be added to this role.

**Comment by dszmaj** [comment]
nope, it also complains about `docker-ce-rootless-extras` so it's definitely much more conditions and safeguards here to do than we think at the moment

it wasn't the case not that long ago, one would install newest containerd, disabled firewalld and all was working just fine, so it seems that they find new ways of blocking docker in rhel 8 every time we find a workaround...

I'm tired of this corporate bs to be honest and I consider jumping ships to debian entirely...

**Comment by dverbeek84** [comment]
I don't see that issue on my fresh 8.3 install

**Comment by dszmaj** [comment]
> I don't see that issue on my fresh 8.3 install

are you able to past what repos you have installed in your system? maybe there is some specific dependency that I don't see right now

**Comment by dverbeek84** [comment]
And hour satellite is synced last weekand, so we have the latest packages.

```
docker-ce-stable                                                                                                          Docker CE Stable - x86_64
rhel-8-for-x86_64-appstream-rpms                                                                                          Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
rhel-8-for-x86_64-baseos-rpms                                                                                             Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
satellite-tools-6.5-for-rhel-8-x86_64-rpms                                                                                Red Hat Satellite Tools 6.5 for RHEL 8 x86_64 (RPMs)
```

**Comment by shakeme** [comment]
> 
> 
> > I don't see that issue on my fresh 8.3 install
> 
> are you able to paste what repos you have installed in your system? maybe there is some specific dependency that I don't see right now

You have to enable the container-tools module for docker 20.x. and update this role to >=3.0.0 in you environment.
`dnf -y module enable container-tools`

**Comment by hamdirhibi** [comment]
The We

**Comment by jomach** [comment]
Same on this side. 

TASK [geerlingguy.docker : Ensure containerd.io is installed.] ***************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failures": ["No package containerd.io available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}
