### ISSUE TITLE
Debian Buster - Package 'docker-ce' has no installation candidate

### ISSUE THREAD

**Issue by liambresnahan** [geerlingguy/ansible-role-docker#270]
Is anyone else seeing issues installing docker on Debian Buster (specifically amd64/x86)? On running this role I get:
`"msg": "No package matching 'docker-ce' is available"` 
It looks like it's missing from the repo (even manually running them from the docker install steps).

**Comment by liambresnahan** [comment]
closed - this was due to an error in distribution I was using

**Comment by palashkulsh** [comment]
getting the same error on ubuntu 20

**Comment by geerlingguy** [comment]
@palashkulsh - Are you running this on an ARM server by any chance?

**Comment by palashkulsh** [comment]
yes oracle aarch64, i think its architecture level issue. that architecture seems to be having lot of issues in everything not just via ansible : )

**Comment by geerlingguy** [comment]
@palashkulsh  See: https://github.com/geerlingguy/ansible-role-docker_arm

**Comment by palashkulsh** [comment]
a big fan of your work. thanks life saviour @geerlingguy .
