### ISSUE TITLE
RHEL 7.9 - container-selinux skipped

### ISSUE THREAD

**Issue by greyfin10** [geerlingguy/ansible-role-docker#287]
__Ansible version:__ Ansible 2.9.21/Tower 3.8.3
__Target Distro:__ Redhat Enterprise Linux 7.9

__Error: Package:__ 3:docker-ce-20.10.8-3.el7.x86_64 (docker-ce-stable)\n  Requires: container-selinux...

__Solution:__ I altered the tasks/setup-RedHat.yml to install container-selinux and containerd.io when the ansible_distribution_major_version >= 7 (instead of ==8), and everything completed.

**Comment by geerlingguy** [comment]
Interesting... researching this a little deeper, it looks like this extra step [may be required on RHEL 7](https://stackoverflow.com/a/45274492), but the default extras repo already contains `container-selinux` on CentOS 7 (https://github.com/docker/for-linux/issues/443#issuecomment-426098056).

It would be great if someone else running RHEL 7 (and not CentOS) could confirm though.

**Comment by greyfin10** [comment]
I DID have to enable rhel-7-server-extras-rpms in order for that to work (forgot to add that).  I'm doing all this through RHSM btw...  so it looked like:

- name: Enable the Redhat Server Extras repository via subscription
  rhsm_repository:
    name: rhel-7-server-extras-rpms
    state: enabled
