### ISSUE TITLE
docker-ce on raspbian 64bit

### ISSUE THREAD

**Issue by stsch83** [geerlingguy/ansible-role-docker#289]
Hi, 

the scrit was not able to install docker-ce on rasbian 64bit version.

TASK [geerlingguy.docker : Add Docker apt key.] **********************************************************************************************************************************************************
ok: [192.168.65.141]

TASK [geerlingguy.docker : Ensure curl is present (on older systems without SNI).] ***********************************************************************************************************************
skipping: [192.168.65.141]

TASK [geerlingguy.docker : Add Docker apt key (alternative for older systems without SNI).] **************************************************************************************************************
skipping: [192.168.65.141]

TASK [geerlingguy.docker : Add Docker repository.] *******************************************************************************************************************************************************
ok: [192.168.65.141]

TASK [geerlingguy.docker : Install Docker.] **************************************************************************************************************************************************************
fatal: [192.168.65.141]: FAILED! => {"changed": false, "msg": "No package matching 'docker-ce' is available"}

Br,
Stefan

**Comment by geerlingguy** [comment]
@stsch83 - For ARM, I have a separate Docker role, since the installation is substantially different: https://github.com/geerlingguy/ansible-role-docker_arm

**Comment by Lithimlin** [comment]
I think by now it's possible to just use apt to install docker-ce or am I seeing this wrong? At least that does work manually (running `apt install docker-ce` on the pi). The resulting docker version is `20.10.13, build a224086`.

**Comment by rienafairefr** [comment]
Ran into roughly this issue, and the only way out of the `No package matching 'docker-ce' is available` was to add :armhf to the packages variables:

        docker_compose_package: docker-compose-plugin:armhf
        docker_packages:
          - "docker-ce:armhf"
          - "docker-ce-cli:armhf"
          - "docker-ce-rootless-extras:armhf"
          - "containerd.io:armhf"
          - "docker-buildx-plugin:armhf"

Traced it to python-apt somehow: `apt install docker-ce` works when running directly on the Pi. But python-apt cache structure has a list of "<packages>:<arch>", at least it does for the docker packages, it may be a bug in python-apt
