### ISSUE TITLE
Role is failing on new install

### ISSUE THREAD

**Issue by digilink** [geerlingguy/ansible-role-docker#298]
I have a new Ubuntu 20.04 host and the role is failing to install with the following error: 

`
TASK [geerlingguy.docker : Add Docker repository.] ******************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt_pkg.Error: E:Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ focal: /usr/share/keyrings/docker-archive-keyring.gpg != , E:The list of sources could not be read.
`

Ansible user I am using to kick the playbook off has full sudo privs, so I don't believe it's a permissions issue. 

I am unsure of how to proceed, I've looked through all the code but nothing sticks out at me. I've used the latest from ansible-galaxy as well as the latest commit here from Github, but the issue persists.

**Comment by geerlingguy** [comment]
Can you check if your playbook updates apt caches? Maybe it needs to do that first. (Or just run on the server `apt-get update`).

**Comment by digilink** [comment]
Thanks Jeff, looks like I'm getting the same error when I issue apt update on the host: 

`E: Conflicting values set for option Signed-By regarding source https://download.docker.com/linux/ubuntu/ focal: /usr/share/keyrings/docker-archive-keyring.gpg !=
E: The list of sources could not be read.`

**Comment by digilink** [comment]
An update on this.... I ran this on another cloud provider (Linode) and ran as expected. I was using an AWS Lightsail VPS initially.

**Comment by kirel** [comment]
For future googlers: I had this problem and it seems to have come from updating to a new version of the role after a loooong time and back in the days it would create a `download_docker_com_linux_ubuntu.list.list` which would sit along with a new`/etc/apt/sources.list.d/docker.list` and confuse the hell out of apt.
