### ISSUE TITLE
Support Docker Compose v2

### ISSUE THREAD

**Issue by fabricat** [geerlingguy/ansible-role-docker#304]
As stated on https://github.com/docker/compose/blob/v2/README.md:

> The installation instructions for Compose V2 differ from V1.
> V2 is not a standalone binary anymore and installation scripts will have to be adjusted.

As an addition, you could also consider installing [compose-switch](https://github.com/docker/compose-switch) to translate V1's `docker-compose ...` commands into V2's `docker compose ...`.

**Comment by geerlingguy** [comment]
Not stale I don't think.

**Comment by JMLX42** [comment]
I can confirm that setting `docker_compose_version: 'v2.0.1'` works as expected.

**Comment by geerlingguy** [comment]
All right, I updated the default, tweaked the download URL to use lowercase `linux` by default, and I think that closes this issue.
