### ISSUE TITLE
Some kind of notification post group add

### ISSUE THREAD

**Issue by impala454** [geerlingguy/ansible-role-docker#308]
Hi Jeff, long time subscriber to your channel, and very much appreciate this role.  I was thinking of submitting a PR for this but curious on your thoughts first.  I use this role to ensure docker is installed on a machine before then pulling some images.  On a fresh build I add my user to the `docker_users` variable and that properly gets set, but if that got changed I need some kind of notification to kick the ssh session or whatever so the user can then actually use docker.  I tried but can't see a way to get such notification without modifying this role (which I happily will let you maintain this role).  Does it make sense to add some kind of notify to this role or is there some way I'm missing to see it changed and take action myself in a task?

**Comment by geerlingguy** [comment]
I can't remember why exactly, but I think I had been testing it and for some reason at least with Docker, that wasn't working for me (or maybe a particular use case for the role)...

**Comment by geerlingguy** [comment]
Heh... oops? https://github.com/geerlingguy/ansible-role-docker/issues/237#issuecomment-832760600

**Comment by impala454** [comment]
I was about to go ahead and PR this but realized in your other closed issue #237 you requested the connection get reset only if user or groups changed.  It appears this is not possible (see [here](https://stackoverflow.com/a/44753457/1544725)).  So I suppose we could either add it to always happen or just skip it altogether.  Up to you.

**Comment by impala454** [comment]
I just ended up adding it to my play after the role call and before my tasks that use docker.
