### ISSUE TITLE
docker_compose_url should be updated in defaults/main.yml

### ISSUE THREAD

**Issue by igorhrcek** [geerlingguy/ansible-role-docker#314]
This is how it looks now:
```
docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
```

This URL does not exist if you want to download the latest Compose, which is v2.1.0. 

The difference is in the uppercase "L" so instead of `docker-compose-Linux-x86_64` it should be `docker-compose-linux-x86_64`, plus the "v" is required before the actual version. This change happened with the release of Compose v2.0.

This is a correct way to create URL now:

```
docker_compose_url: https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64

**Comment by geerlingguy** [comment]
Merging into https://github.com/geerlingguy/ansible-role-docker/issues/314 — please leave this info there and hopefully I or someone else will be able to drop a PR to update this.
