### ISSUE TITLE
ansible-lint yaml warning: truthy value should be one of [false, true]

### ISSUE THREAD

**Issue by kare** [geerlingguy/ansible-role-docker#325]
I have `ansible-role-docker` installed in my playbook and when I run command `ansible-lint playbook.yaml` I get the following warning:
```
yaml: truthy value should be one of [false, true] (truthy)
roles/geerlingguy.docker/tasks/docker-compose.yml:5
```

I don't expect to see any warnings from `ansible-lint`.

**Comment by geerlingguy** [comment]
Just a warning, but I do see the same in the CI runs:

https://github.com/geerlingguy/ansible-role-docker/runs/4751950065?check_suite_focus=true

I'd be happy to accept a PR that changes the `no` to `false`.
