### ISSUE TITLE
add Rocky Linux

### ISSUE THREAD

**Issue by vandsten** [geerlingguy/ansible-role-docker#345]
There is support with RedHat but not for Rocky Linux. Rocky Linux return ansible_os_family string "Rocky". Adding setup-Rocky.yml and change in main.yml file is probably enough.

**Comment by geerlingguy** [comment]
I am testing on Rocky Linux (see https://github.com/geerlingguy/ansible-role-docker/blob/master/.github/workflows/ci.yml#L44) and it's working. There may have been a bug in earlier versions of Ansible but with the latest versions of Ansible this role works fine on Rocky and Alma.
