### ISSUE TITLE
Docker installation fails in Arch Linux for Ansible >= 2.12

### ISSUE THREAD

**Issue by adamantike** [geerlingguy/ansible-role-docker#346]
Related logs:
> TASK [geerlingguy.docker : Install Docker (Ansible >=2.12).] *******************************************************************
> fatal: [host]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.pacman) module: allow_downgrade. Supported parameters include: remove_nosave, executable, upgrade, update_cache_extra_args, state, upgrade_extra_args, update_cache (update-cache), extra_args, force, name (package, pkg)."}

Root cause is #336, as the introduced parameter `allow_downgrade` is not supported by the `pacman` manager module.

**Comment by amotl** [comment]
Dear Michael and Jake,

sorry for the annoyance. #353 might have a fix, can I humbly ask you to test it in order to confirm it works before un-drafting the PR?

With kind regards,
Andreas.

**Comment by RealOrangeOne** [comment]
Your patch is worked perfectly for me: https://github.com/geerlingguy/ansible-role-docker/pull/352#issuecomment-1129685797

**Comment by amotl** [comment]
Thank you Jake and sorry for the delay. I've just flagged #352 for review.

**Comment by amotl** [comment]
Dear @adamantike,

@RealOrangeOne confirmed that my fix #352 worked and @geerlingguy was so nice to integrate it and publish a new release. So, I think this issue can be closed.

With kind regards,
Andreas.

**Comment by adamantike** [comment]
Thanks a lot for your quick resolution, @amotl!

I was just able to test the fix, and can also confirm it is working as expected. For anyone else experiencing this issue, version `4.2.3` is the first one to include @amotl's fix.

Glad to close this issue, thanks again!
