### ISSUE TITLE
support docker compose installation as a docker cli 'plugin'

### ISSUE THREAD

**Issue by distributev** [geerlingguy/ansible-role-docker#355]
docker compose comes now as a docker cli 'plugin' and can be installed as such.

https://docs.docker.com/compose/install/

https://docs.docker.com/engine/reference/commandline/plugin/

Some newer applications already assume docker compose to be installed as a 'plugin' and will not work when docker-compose is installed with this role. In the future the old docker-compose will be deprecated in favor of the new p

**Comment by kaysond** [comment]
@geerlingguy would you take a PR for this?

The plugin is now published in docker's apt repo (see https://docs.docker.com/engine/install/debian/#install-docker-engine) so it's an easy add.

**Comment by geerlingguy** [comment]
Yes!
