### ISSUE TITLE
Support for amazon linux 2

### ISSUE THREAD

**Issue by dasimmet** [geerlingguy/ansible-role-docker#357]
This role does not work for amazon linux 2 in AWS EC2 Instances.
Since it's yum based, it will install the docker repo for centos version 2, which does not exist.

Docker on amazon is usually installed using:
amazon-linux-extras install -y docker

**Comment by rejifald** [comment]
Also missing amazon linux 2 support.

**Comment by sasidatta** [comment]
@geerlingguy This might require multiple changes related to CentOS task files . Do you think is it a good add on for this role?

**Comment by shemi-plgs** [comment]
Also needing support for amazon linux 2

**Comment by zeevo** [comment]
Can confirm this fails out-of-the-box. Would love if mazon Linux 2 was supported!

**Comment by geerlingguy** [comment]
It could be possible to support Amazon Linux 2, but I would only like to add that on if it doesn't add a ton of overhead. Especially if we could break out the special install steps a bit so they don't interfere with the other 99% of RHEL-derivative OSes.

**Comment by khismatullinmax** [comment]
Hope it will be helpful for someone with my little changes to deploy docker into Amazon Linux - https://github.com/geerlingguy/ansible-role-docker/pull/408.
I checked a new role on empty EC2 instance and on running EC2 instance.
