### ISSUE TITLE
install docker-compose using DEB/RPM official package

### ISSUE THREAD

**Issue by fabricat** [geerlingguy/ansible-role-docker#366]
It is possible to install `docker-compose` using the `docker-compose-plugin` package, see [here](https://docs.docker.com/compose/install/compose-plugin/#install-using-the-repository).

This alternative method avoids manually setting the `docker_compose_version` variable, and makes upgrades easier.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-docker/issues/355
