### ISSUE TITLE
ansible-role-docker should drop docker-ee entirely as it is no longer provided in the docker repos.

### ISSUE THREAD

**Issue by danielwoodz** [geerlingguy/ansible-role-docker#387]
This is not a request to fix the issue, as I'm not sure it would be worth the effort.

Mirantis has removed docker-ee (now known as Mirantis Container Runtime) from the normal repos, it is available from https://repos.mirantis.com/, but only docker-ee. 

Additionally, the docker compose plugin is not available at all in the Mirantis repo, which complicates moving to basing things on the plugin instead of the separate golang binary from GitHub.

Finally, many architectures are missing from docker-ee, and sources are not available universally. 

It would be better for maintainability for this project to drop the already broken docker-ee instead of making all of conditionals to handle the self-inflicted edge cases created by Mirantis.

**Comment by geerlingguy** [comment]
Yeah, honestly I've never used docker-ee anywhere... I'd be okay with it not being supported by this role.
