### ISSUE TITLE
Missing requirement to run playbook

### ISSUE THREAD

**Issue by sgommaraschi** [geerlingguy/ansible-role-docker#391]
**Ansible version => ansible [core 2.12.2]
Package => ansible-core-2.12.2-4.el8_6.x86_64**

TASK [geerlingguy.docker : Load OS-specific vars.] **********************************************************************************************************
ok: [HOST] => {"ansible_facts": {}, "ansible_included_var_files": ["/usr/share/ansible/roles/geerlingguy.docker/vars/main.yml"], "changed": false}

TASK [geerlingguy.docker : include_tasks] *******************************************************************************************************************
fatal: [HOST]: FAILED! => {"reason": "couldn't resolve module/action 'ini_file'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/usr/share/ansible/roles/geerlingguy.docker/tasks/setup-RedHat.yml': line 23, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure Docker Nightly repo.\n  ^ here\n"}

Googling seems that this module is out of ansible-core package

https://docs.ansible.com/ansible/latest/collections/community/general/ini_file_module.html
_

> This module is part of the [community.general collection](https://galaxy.ansible.com/community/general) (version 5.8.0).
> You might already have this collection installed if you are using the ansible package. It is not included in ansible-core. To check whether it is installed, run ansible-galaxy collection list.

_

So I run `ansible-galaxy collection install community.general -p /usr/share/ansible/roles`
After installation of community.general collection it works

**Comment by geerlingguy** [comment]
I generally recommend people install Ansible via Pip: `pip3 install ansible`, and this gives you all the necessary collections.

Unfortunately, there's no way to identify collection dependencies from within roles, so if you want to install just ansible-core without full Ansible, you will need to install the appropriate collections as well.
