### ISSUE TITLE
"No package matching 'docker-ce' is available" on Raspberry OS Lite Bullseye 64bit

### ISSUE THREAD

**Issue by paranerd** [geerlingguy/ansible-role-docker#402]
Hi,

I keep getting the above error on a fresh install of Raspberry OS Lite Bullseye (64bit).
Checked out "ansible-role-docker_arm" and it says that "ansible-role-docker" has full support for arm64 by now.
All is fine when going the manual route with the "get-docker.sh" convenience script, though.

Any suggestions? I would really love to use this role to automate Docker installation over the "_arm" version as it provides some crucial advantages (like configuring Docker daemon options)

Thanks in advance!

**Comment by paranerd** [comment]
Sure, here you go:
- ansible_architecture: aarch64
- docker_apt_arch: amd64
- docker_apt_repository: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable

**Comment by paranerd** [comment]
Did some testing and have some confusing findings:

When I set `docker_apt_arch: arm64` manually, everything seems to work fine. This was to be expected.

The confusing part comes here:
Having `docker_apt_arch2: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"` in my `vars:` I get the expected `arm64`.

**Comment by j-koehler** [comment]
> When I set docker_apt_arch: arm64 manually, everything seems to work fine. This was to be expected.

Yeah back in the days™ i used this. 

I still have 

````
docker_compose_arch: armv7
docker_apt_arch: armhf
```

configured. 

This is really strange. I can not spot any obvious error and unfortunately my Ansible knowledge ends here (working just fro looking at things without trying it out - and I don't have a spare Raspi to actually try it/not enough experience to use Ansible to "provision" a running Docker container)

From my perspective you could easily solve this by just setting/overwriting `docker_apt_arch`, no? Bit hacky solution but maybe the fastest way to get things done.

**Comment by paranerd** [comment]
Thank you for looking into this.
I will probably go with the workaround of setting `docker_apt_arch: arm64` manually.
Still keeping this issue open, maybe someone else stumbles upon it 😊

**Comment by j-koehler** [comment]
What you could do: run in dry and verbose mode, maybe you can see something from this or post the logfile.

**Comment by DJviolin** [comment]
`docker_apt_arch: arm64` did the trick for me, too! Thank You!

**Comment by danscarf** [comment]
This worked for me, too:

```
become: yes
  vars:
    docker_apt_arch: arm64
    docker_users:
    ...
```
Thank you
