### ISSUE TITLE
Run playbook

### ISSUE THREAD

**Issue by chanyshev** [geerlingguy/ansible-role-docker#416]
Example Playbook
```
- hosts: all
  roles:
    - geerlingguy.docker
 ```
In this form, the playbook will not start. I think it should be like this
```
- hosts: all
  roles:
    - ansible-role-docker
```

**Comment by geerlingguy** [comment]
The example playbook assumes you have installed the role via Ansible Galaxy (e.g. `ansible-galaxy install -r geerlingguy.docker`).
