### ISSUE TITLE
Idempotence test failed

### ISSUE THREAD

**Issue by waja** [geerlingguy/ansible-role-docker#417]
Hi,

when using this role, the molecule Idempotence fails:

```
CRITICAL Idempotence test failed because of the following tasks:
*  => geerlingguy.docker : Delete existing docker-compose version if it's different.
WARNING  An error occurred during the test sequence action: 'idempotence'. Cleaning up.
```

It would be very welcomed if the very bad documented [molecule-idempotence-notest](https://www.google.de/search?q=%22molecule-idempotence-notest%22) tag could be used.

Many thanks Jan

**Comment by geerlingguy** [comment]
CI doesn't seem to have that issue: https://github.com/geerlingguy/ansible-role-docker/actions/runs/5234120583/jobs/9450047572

Perhaps the environment where you're running the test is a little different?
