### ISSUE TITLE
docker-compose-plugin install fails on arch

### ISSUE THREAD

**Issue by cvonderstein** [geerlingguy/ansible-role-docker#427]
As the title says, the `Install docker-compose plugin` task fails on Arch Linux (not sure for how long, but about a week ago it still worked. The Error message is `error: 'docker-compose-plugin': could not find or read package`, so I guess that the package was renamed or replaced, although I couldn't find any more information on that.

For now, I temporarily solved this by removing the task manually from the file, but that is of course not a permanent solution.

**Comment by geerlingguy** [comment]
Can you fix this by adding:

```yaml
docker_install_compose: true
docker_install_compose_plugin: false
```

See: https://github.com/geerlingguy/ansible-role-docker/pull/369

**Comment by cvonderstein** [comment]
Works (after applying https://github.com/spantaleev/matrix-docker-ansible-deploy/commit/a40cb963a9254b138af7d7f796002efae884bc59, which is the fix for the related https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/2924, which is exactly how I stumbled upon this issue) and the playbook runs through normally again.

I'm not sure how this is related to #369 though, since this issue is about manual and playbook installations of docker compose? Or am I missing a point?

Thanks for helping though!

**Comment by cvonderstein** [comment]
Sorry, I think I was a little bit too fast with closing, since this is more of a workaround than a fix. Probably shouldn't do this stuff at 3am...

**Comment by cschindlbeck** [comment]
I think this should fix it 

https://github.com/geerlingguy/ansible-role-docker/pull/439

works for me, please someone check as arch appears not to be covered by molecule

**Comment by cschindlbeck** [comment]
this issue is not stale, @geerlingguy can you approve https://github.com/geerlingguy/ansible-role-docker/pull/439 ?
