### ISSUE TITLE
geerlingguy.docker was NOT installed successfully

### ISSUE THREAD

**Issue by jayvs6341** [geerlingguy/ansible-role-docker#429]
Hello Team,

Suddenly, my gitlab pipeline stopped working. Previously it was working. I am getting following errors.

 [WARNING]: - geerlingguy.docker was NOT installed successfully: missing
required 'current_version' from server response
(https://galaxy.ansible.com/api/)
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
ERROR: Job failed: exit code 1

**Comment by bdsoha** [comment]
@jayvs6341 This is probably not related to the package, but due with the update to Ansible Galaxy *(a.k.a **NG**)*.
When manually visiting the role's page and clicking `Versions`, I also get a `404`.

**Comment by geerlingguy** [comment]
See also: https://www.jeffgeerling.com/blog/2023/ansible-galaxy-error-unable-compare-role-versions

Hopefully this gets fixed soon! Also related: https://github.com/geerlingguy/ansible-role-pip/issues/60 and https://github.com/ansible/galaxy_ng/pull/1946
