### ISSUE TITLE
GPG keys should not be saved to `/apt/trusted.gpg.d` / Do not use `apt-key`

### ISSUE THREAD

**Issue by kawadeomkar** [geerlingguy/ansible-role-docker#435]
As per https://wiki.debian.org/DebianRepository/UseThirdParty, third party keys should not be placed in `/etc/apt/trusted.gpg.d`.
From the Wiki:
```
If future updates to the certificate will be managed by an apt/dpkg package as recommended below, then it SHOULD be downloaded into /usr/share/keyrings using the same filename that will be provided by the package. If it will be managed locally , it SHOULD be downloaded into /etc/apt/keyrings instead.
```

I noticed that the docker docs installation guide https://docs.docker.com/engine/install/debian/ places the docker GPG keys 
in `/etc/apt/keyrings`. 

Also, `apt-key` is deprecated and will not be available after Debian 11 / Ubuntu 22.04. 
Instead of  `apt-key add -` https://github.com/geerlingguy/ansible-role-docker/blob/8ff4a241477f5f24c718d606a2ee450b370cc47c/tasks/setup-Debian.yml#L47
this should be `sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg`

I've started working on the proposed changes, and will make a PR shortly

**Comment by bryion** [comment]
This worked for me.
