### ISSUE TITLE
 Feature request - select docker version

### ISSUE THREAD

**Issue by bartmeuris** [geerlingguy/ansible-role-docker#45]
Currently there's no option to specify a specific docker version, which is desired in the case for something like a Kubernetes (which at the moment requires a 17.03.x version), or keeping all installations consistent across a set of servers without necessarily moving them all to the latest version.

At the moment I fixed this by overriding the `docker_package` variable for those specific hosts like this, but this only works for Ubuntu hosts:

```
# Explicitly set the version of docker to be installed to the one here:
docker_version: '17.03.2'
docker_package: 'docker-{{docker_edition}}={{docker_version}}~{{docker_edition}}-0~{{ansible_distribution|lower}}-{{ansible_distribution_release}}'
```

Not sure how this would be handled best, but you need some version specific handling per distribution, since the "version" part of the package name already uses a different separator between `apt` (which uses `=`) and `yum` (which uses `-`).

It would be nice if this could be generalized somehow, but I don't need `yum` support at the moment, so my 'quick hack' works at the moment.

**Comment by josdotso** [comment]
This is a great idea.  Pinning versions of things is a great for stability.

**Comment by CumpsD** [comment]
Turns out the latest on ubuntu is called `18.05.0~ce~3-0~ubuntu` so the above fails (because of the 3-0 instead of just 0)

What does it actually mean, the 3-0?

**Comment by ahulab** [comment]
I recently spend about 25 minutes on this before realizing my issue was that I needed to use a `=` vs. `-`. Setting `docker_package: "docker-{{ docker_edition }}=18.06.0~ce~3-0~ubuntu"` worked

Is it possible that a change to the documentation is all that is needed? It could just be revised to say that the package format will change depending on whether you are using apt or yum? And then users can change the `docker_package` accordingly. 

It could also be a good idea to give instructions on finding the list of available versions of the package, since they aren't 1-to-1 with release names or the output of `docker --version` 

For instance, on ubuntu: `apt-cache madison docker-ce`

**Comment by mstenta** [comment]
I documented how I pinned my docker-ce version over here: https://github.com/geerlingguy/ansible-role-docker/issues/85#issuecomment-415765758 (using a variation of the variables from @bartmeuris above, along with a new apt pinning preference in /etc/apt/preferences.d/docker).

**Comment by exequielrafaela** [comment]
From the role var:       
`docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"`

it's possible to infere the actual docker repo url so as to check the exact names for the currently available <VERSION> for every linux distro. For instance if you're looking for Ubuntu Xenial (16.04) docker packages: https://download.docker.com/linux/ubuntu/dists/xenial/stable/binary-amd64/Packages

- Version: 17.03.0~ce-0~ubuntu-xenial
- Version: 17.03.1~ce-0~ubuntu-xenial
- Version: 17.03.2~ce-0~ubuntu-xenial
- Version: 17.03.3~ce-0~ubuntu-xenial
- Version: 17.06.0~ce-0~ubuntu
- Version: 17.06.1~ce-0~ubuntu
- Version: 17.06.2~ce-0~ubuntu
- Version: 17.09.0~ce-0~ubuntu
- Version: 17.09.1~ce-0~ubuntu
- Version: 17.12.0~ce-0~ubuntu
- Version: 17.12.1~ce-0~ubuntu
- Version: 18.03.0~ce-0~ubuntu
- Version: 18.03.1~ce-0~ubuntu
- Version: 18.06.0~ce~3-0~ubuntu
- Version: 18.06.1~ce~3-0~ubuntu
- Version: 5:18.09.0~3-0~ubuntu-xenial

As a result we can literally use the versions listed above or construct them taking advantage of the current vars of the role as a shortcut. Some variants depending on different versions below:

`docker_package: "docker-{{ docker_edition }}=18.06.0~ce~3-0~ubuntu"
docker_package: "docker-{{ docker_edition }}=18.06.0~{{docker_edition}}~3-0~{{ansible_distribution|lower}}"`

`docker_package: "docker-{{ docker_edition }}=5:18.09.0~3-0~ubuntu-xenial"
docker_package: "docker-{{ docker_edition }}=5:18.09.0~3-0~{{ansible_distribution|lower}}-{{ ansible_distribution_release }}"`

NOTE: This does not exactly corresponds with the official doc VERSIONS https://docs.docker.com/v17.12/release-notes/docker-ce/

**Comment by anmoel** [comment]
please merge pull-request #96 for this feature

**Comment by mstenta** [comment]
@anmoel Does your pull request also handle pinning the version? If not, then running apt-get upgrade manually would also upgrade Docker, correct?

I described how I managed to pin the Docker version (using apt) here: https://github.com/geerlingguy/ansible-role-docker/issues/85

I think we either need to reopen #85 to fix pinning there, or include it in this issue/pull request for it to be a complete solution. This is all going off of memory (and my old comments), so correct me if I'm wrong...

**Comment by anmoel** [comment]
@mstenta it's not handling the pinning.
this pull-request allows the installation of a selected version. It is compatible with the supported os.
you can set a docker version like '18.06.0' or '18.06'.
in the second case it would install the latest patch level.
i need this for kubernetes, because k8s not support every latest version.

in my opinion, pinning is another feature and is not part of the scope of this issue

**Comment by mstenta** [comment]
@anmoel Great that makes sense. I'm not able to re-open the #85 issue - @geerlingguy can you?

@anmoel will this change affect existing users? Will I need to change anything in my Ansible role? (will this break my current approach?)

This is what I am currently doing to force a specific version:

```
docker_version: 17.03.0
docker_package_version: "{{docker_version}}~{{docker_edition}}-0~{{ansible_distribution|lower}}-{{ansible_distribution_release}}"
docker_package: "docker-{{docker_edition}}={{docker_package_version}}"
```
