### ISSUE TITLE
Deprecated use of `includes`

### ISSUE THREAD

**Issue by jevonearth** [geerlingguy/ansible-role-docker#46]
When using this role, the user gets warnings as follows;

```
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or
'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
```

There are currently three pull requests that fix this issue:

* #37 
* #39 
* #41 

It may make sense to wait a couple more releases before making this merge as pointed out in comments on #37 

I'm opening this ticket so people find this before opening another PR. :)

**Comment by geerlingguy** [comment]
Merged https://github.com/geerlingguy/ansible-role-docker/pull/37 and this fix will be in the next release. Note that I was waiting for 2.5 to be released to give people time to upgrade their playbooks at least to 2.4, since that's the minimum requirement for this change.
