### ISSUE TITLE
Recent role update does not remove previous versions of the apt key, and so duplicate apt keys are created on Debian

### ISSUE THREAD

**Issue by danrough** [geerlingguy/ansible-role-docker#460]
In #436 the path that the Docker apt key was changed from `/etc/apt/trusted.gpg.d/` to `/etc/apt/keyrings`. For those of us who favour always using the latest version of the role, rather than pinning a specific version, this means that the key that the role previously installed in `/etc/apt/trusted.gpg.d/` remains and so a duplicate is created. This then results in errors from apt when running `apt update`, for e.g.

**Comment by cschindlbeck** [comment]
Something along the lines of https://github.com/geerlingguy/ansible-role-docker/pull/464 could help, although i don't like the code duplication in the vars
