### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-docker#52]
Ensure depdencies are installed

https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/setup-Debian.yml#L10

**Comment by geerlingguy** [comment]
This was fixed in https://github.com/geerlingguy/ansible-role-docker/commit/309ab2caeee55ae1ff2cc096c8176d43ffe42c58#diff-ebbe0c3ff3753db31a12af649c45a099
