### ISSUE TITLE
Docker install failing on RedHat 7.x

### ISSUE THREAD

**Issue by AlbanAndrieu** [geerlingguy/ansible-role-docker#56]
Issues on ansible is 

Error: Package: docker-ce-18.03.0.ce-1.el7.centos.x86_64 (docker-ce-stable)\n           Requires: container-selinux >= 2.9\n

Can be easily reproduced on the server doing

```
yum install docker-ce
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:18.03.0.ce-1.el7.centos will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-18.03.0.ce-1.el7.centos.x86_64
--> Processing Dependency: pigz for package: docker-ce-18.03.0.ce-1.el7.centos.x86_64
--> Running transaction check
---> Package docker-ce.x86_64 0:18.03.0.ce-1.el7.centos will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-18.03.0.ce-1.el7.centos.x86_64
---> Package pigz.x86_64 0:2.3.4-1.el7 will be installed
--> Finished Dependency Resolution
Error: Package: docker-ce-18.03.0.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2.9
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: docker-ce-18.03.0.ce-1.el7.centos.x86_64 (docker-ce-stable)
           Requires: container-selinux >= 2.9
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Changing notify_only to 0  in /etc/yum/pluginconf.d/search-disabled-repos.conf is fixing it.
Can we automate this? Or can I bypass this?

**Comment by geerlingguy** [comment]
AWS is a bit different; they have their own oddities with RHEL-based Amazon Linux (unless you're using a RHEL distro on AWS?

This is working in the CentOS tests, so I'm wondering if there's some simpler way of resolving it without enabling an entire extra repo?

**Comment by grugnog** [comment]
The RHEL official AMIs on AWS use the rhui-REGION-rhel-server-extras style repo names, rather than the rhel-7-server-extras-rpms one (I assume so they can point at a mirror that only responds to AWS requests that have a valid license).

**Comment by webyneter** [comment]
FWIW, these are the extra dependencies I had to install prior to running this role for the latter to succeeed on Amazon Linux 2 (hvm, ebs-backed):

```yaml
# region accounting for the fact that geerlingguy.docker does not account for CentOS dependencies
  - name: Install Docker CE CentOS-specific dependencies
    block:
    # region https://docs.docker.com/install/linux/docker-ce/centos/#set-up-the-repository
    - name: Install yum-utils
      package:
        name: yum-utils
        state: present
    - name: Install device-mapper-persistent-data
      package:
        name: device-mapper-persistent-data
        state: present
    - name: Install lvm2
      package:
        name: lvm2
        state: present
    # endregion
    # region https://github.com/docker/for-linux/issues/299#issuecomment-390976518
    - name: yum makecache fast
      shell: yum makecache fast
    - name: Install container-selinux
      shell: yum install -y http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm
    # endregion
    # endregion
```

**Comment by lanycrost** [comment]
I think these problem should fix docker...

I have this problem don't only inside RHEL and Amazon Linux. I have this problem in another RPM based operating systems such as Oracle Linux. I don't understand their version game, but I think he can fix it :satisfied:

https://github.com/docker/for-linux/issues/443

**Comment by allir** [comment]
> This is working in the CentOS tests, so I'm wondering if there's some simpler way of resolving it without enabling an entire extra repo?

Installing docker-ce on RedHat has a dependency to the "container-selinux" package which is not provided in the server-rpms repo, but is in the extras repo.

It's possible to use the "--enablerepo" option in yum to only enable the extras repo for a single command.
```bash
yum --enablerepo rhel-7-server-extras-rpms container-selinux
```

The yum ansible module provides this as well. <https://docs.ansible.com/ansible/latest/modules/yum_module.html>
Example:
```yaml
- name: install container-selinux dependency
  yum:
    name: container-selinux
    enablerepo: rhel-7-server-extras-rpms
    state: present
```

This would in turn install the package without globally enabling the repo.

Another way would be to install it direcly from rpm via http://mirror.centos.org/centos/7/extras/x86_64/Packages/

**Comment by Fixmetal** [comment]
This is still present in RHEL 7.8.
