### ISSUE TITLE
docker_yum_repo_url changed,can't install docker-ce

### ISSUE THREAD

**Issue by syoujiang** [geerlingguy/ansible-role-docker#73]
https://download.docker.com had been block ,so I　change to aliyun.
follow is my conf in vars,but it can't install docker-ce
# Used only for RedHat/CentOS/Fedora.
docker_yum_repo_url: http://mirrors.aliyun.com/docker-ce/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: 0
docker_yum_repo_enable_test: 0

**Comment by geerlingguy** [comment]
@syoujiang - If download.docker.com is blocked, that sounds like a local network issue; I would work with your network administrator to allow it so you can download through the official channels.

This isn't something I think I'd want to change as a default for all users of the role.
