### ISSUE TITLE
Feature Request - Swarm clustering

### ISSUE THREAD

**Issue by colonelpopcorn** [geerlingguy/ansible-role-docker#75]
I've had some trouble getting your Kubernetes role to work in a Vagrant environment so I decided to try Docker Swarm and it was a whole lot easier to create a cluster. Yeah, I know it's not as complicated but it would be nice to have some functionality similar to your Kubernetes role in this role. I've got an idea on how to set it up and I'd like to get a pull request in for it. Please let me know if this something you'd be interested in having as a part of this role.

**Comment by geerlingguy** [comment]
Haha, I have stories—_many_ horrible, war stories—from getting Kubernetes running on Vagrant. But here are a couple examples where I do have it working after working through some fun networking things...

  - https://github.com/geerlingguy/ansible-for-devops/tree/master/kubernetes
  - https://github.com/geerlingguy/raspberry-pi-dramble

As mentioned in the PR, I would rather not add swarm support to _this_ role, but rather I think it should be a simple but separate role.

**Comment by colonelpopcorn** [comment]
I published my own role [here](https://github.com/colonelpopcorn/ansible-role-docker-swarm). However, it seems I might have duplicated some other roles. Still, I think it was a good learning experience. Thanks!
