### ISSUE TITLE
Add `docker` python package

### ISSUE THREAD

**Issue by triplepoint** [geerlingguy/ansible-role-docker#8]
It's plausible someone is installing this role because they're planning to execute an Ansible `docker_container` task, however this task depends on the python `docker` package to function.

It'd be great if this role added this package directly, to avoid having to check for it in dependent roles.

**Comment by geerlingguy** [comment]
Yeah... and I just ran into:

```
TASK [Build Docker image from Dockerfiles.] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to import docker-py - No module named requests.exceptions. Try `pip install docker-py`"}
```

That happened during a [test run](https://travis-ci.org/geerlingguy/ansible-for-devops/jobs/236586398) of the code backing an example in Ansible for DevOps. It would definitely be convenient to have this role be a one-stop shop for installing `docker-py`...

**Comment by geerlingguy** [comment]
...but as I mentioned in [this PR comment](https://github.com/geerlingguy/ansible-role-docker/pull/9#issuecomment-302974457), it's probably more architecturally sound to split that off into a `pip` role. Therefore, I present to you: https://github.com/geerlingguy/ansible-role-pip

To get `docker-py`, you can add the role `geerlingguy.pip`, and in your playbook variables, set:

```yaml
pip_install_packages:
  - name: docker-py
    version: "1.10.6"
```

I'm going to add a note to that effect in this role's documentation/README before closing out this issue, though.

**Comment by triplepoint** [comment]
Right on, I had a similar role being copypasta'ed between a few different projects; probably worth scraping that out and replacing it with a published dependency.  Thanks for taking care of the documentation, I can call this one resolved.

**Comment by geerlingguy** [comment]
Perfect! I updated the documentation in the commit above.

**Comment by triplepoint** [comment]
Did you specifically mean `docker-py` and not `docker`?  It looks like the `docker-py` project renamed their package near the end of last year, with their 2.0 release.
https://docker-py.readthedocs.io/en/stable/change-log.html#

**Comment by geerlingguy** [comment]
Gah! The level of renames that occur in the Docker ecosystem is annoying.

I'll update the docs and usage...
