### ISSUE TITLE
[Centos7] Install of docker-compose

### ISSUE THREAD

**Issue by wjeanniard-yseop** [geerlingguy/ansible-role-docker#94]
Hello,

For strange reasons, when I install docker and docker-compose with this role, the docker-compose binary is not available for all users. It work with the 'root' user but not with users with restricted privileges (i believe this is a $PATH issue).

I have solved the problem by creating a symlink to the current binary:  
`ln -s /usr/local/bin/docker-compose /bin/docker-compose`.

I can add the symlink to the role, but maybe there is a better way ?

I use a fresh VM with minimal installation of the latest Centos7.

**Comment by gbstan92** [comment]
Same issue here. Your solution worked for me.
